
import Providers from "@/components/Providers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Vendor Hierarchy Management",
  description: "Generated by create next app",
};









export default function RootLayout({ children }) {


  return (
    <Providers >
      <html lang="en">
        <body className="antialiased">
          <Navbar />
          <main className="p-6">{children}</main>
        </body>
      </html>
    </Providers>
  
  );


}
